'Test for function 100 lazy_matrix_mul'
'Function to be tested: lazy_matrix_mul(matrix, matrix)'
 
>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

'Matrix of integers'
>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])

#test_2
>>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
array([[13, 16]])


#test_4
>>> lazy_matrix_mul([[1, 2, 3], [4, 5, 6]], [[1], [2], [3]])
array([[14],
       [32]])

#test_5
>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]])
array([[19, 22],
       [43, 50]])


>>> lazy_matrix_mul(" Holberton", [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead


>>> lazy_matrix_mul([[5, 6], [7, 8]], "Holberton")
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead


>>> lazy_matrix_mul([[]], [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)


>>> lazy_matrix_mul([[5, 6], [7, 8]], [[]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)


>>> lazy_matrix_mul([[5, "6"], [7, 8]], [[5, 6], [7, 8]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[5, 6], [7, 8]], [[5, "6"], [7, 8]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[5, 6, 10], [7, 8]], [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.


>>> lazy_matrix_mul([[5, 6], [7, 8]], [[5, 6, 1], [7, 8]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2, 3], [3, 4, 5]], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


>>> lazy_matrix_mul([1])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> lazy_matrix_mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> lazy_matrix_mul([[1, 2], [3, 4], [3, 4]] [[5, 6, 1], [7, 8, 2]])
Traceback (most recent call last):
TypeError: list indices must be integers, not tuple